### PR TITLE
Fix: resolved missing Helpers\Helper class issue in views

### PR DESCRIPTION
**Pull request by krudi**
This PR fixes an issue where footer.blade.php and chat.blade.php were throwing an error due to a missing Namu\WireChat\Helpers\Helper class. This happened while testing the package after installation.

Screenshot 2024-12-09 191354

### CODE REVIEW

**Review by zerkbro — APPROVED** [review]
This looks fine for me.

**Review by namumakwembo — CHANGES_REQUESTED** [review]
Hi @krudi,

Thank you for fixing the typo — great catch!

I noticed that your pull request includes several  formatting changes, such as line shifts, spaces, and other edits that don't affect the functionality. These can potentially cause merge conflicts, especially since I'm also working on updates to the same files. To avoid conflicts, could you please update the PR to include only the relevant code changes and remove any unrelated formatting adjustments?

Thanks again for your contribution!

**Comment by zerkbro** [comment]
@namumakwembo Instead of this can you directly push the fix instead in the latest version. That will be much faster TBH.

**Comment by namumakwembo** [comment]
Fix  #11

**Pull request closed without merging**
